import type { AuditReport } from '../auditors/types.js';
import { getGradeEmoji, getSeverityEmoji } from '../scoring/risk.js';

export function renderMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  // ─── Header ───────────────────────────────────────────────────────
  lines.push('# 🩺 ASC Doctor Report');
  lines.push('');
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **App** | ${report.appName} (\`${report.bundleId}\`) |`);
  lines.push(`| **Version** | ${report.version} (${report.platform}) |`);
  lines.push(`| **Date** | ${report.date} |`);
  lines.push(`| **Risk Score** | **${report.score}/100** ${getGradeEmoji(report.score)} **${report.grade}** — ${report.gradeLabel} |`);
  lines.push('');

  // ─── Summary Table ────────────────────────────────────────────────
  lines.push('## Summary');
  lines.push('');
  lines.push('| Module | 🔴 Critical | 🟠 High | 🟡 Warning | ℹ️ Info |');
  lines.push('|--------|:-----------:|:-------:|:----------:|:------:|');

  for (const result of report.results) {
    const c = result.findings.filter((f) => f.severity === 'critical').length;
    const h = result.findings.filter((f) => f.severity === 'high').length;
    const w = result.findings.filter((f) => f.severity === 'warning').length;
    const i = result.findings.filter((f) => f.severity === 'info').length;

    const status = c + h + w === 0 ? ' ✅' : '';
    lines.push(`| ${result.icon} ${result.label}${status} | ${c || '—'} | ${h || '—'} | ${w || '—'} | ${i || '—'} |`);
  }

  lines.push('');

  // ─── Findings by Severity ────────────────────────────────────────
  const severityOrder = ['critical', 'high', 'warning', 'info'] as const;
  const severityLabels = {
    critical: '🔴 Critical Findings',
    high: '🟠 High Findings',
    warning: '🟡 Warnings',
    info: 'ℹ️ Informational',
  };

  for (const severity of severityOrder) {
    const findings = report.findings.filter((f) => f.severity === severity);
    if (findings.length === 0) continue;

    lines.push(`## ${severityLabels[severity]}`);
    lines.push('');

    for (const finding of findings) {
      const emoji = getSeverityEmoji(finding.severity);
      lines.push(`### ${emoji} [${finding.id}] ${finding.title}`);
      lines.push('');
      lines.push(finding.message);
      lines.push('');
      if (finding.remedy) {
        lines.push(`> **Fix:** ${finding.remedy}`);
        lines.push('');
      }
    }
  }

  // ─── Passed Checks ──────────────────────────────────────────────
  const passedModules = report.results.filter(
    (r) => r.findings.filter((f) => f.severity !== 'info').length === 0,
  );

  if (passedModules.length > 0) {
    lines.push('## ✅ Passed Checks');
    lines.push('');
    for (const mod of passedModules) {
      lines.push(`- ${mod.icon} ${mod.label}`);
    }
    lines.push('');
  }

  // ─── Footer ──────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [ASC Doctor](https://github.com/aykutbey3543/ascdoc)*');
  lines.push('');

  return lines.join('\n');
}
