import chalk from 'chalk';
import type { AuditReport } from '../auditors/types.js';
import { getGradeEmoji, getSeverityEmoji } from '../scoring/risk.js';

export function renderTerminal(report: AuditReport): string {
  const lines: string[] = [];

  // ─── Header ───────────────────────────────────────────────────────
  lines.push('');
  lines.push(chalk.bold('  🩺 ASC Doctor Report'));
  lines.push(chalk.dim('  ─────────────────────────────────────────'));
  lines.push(`  ${chalk.dim('App:')}      ${chalk.white.bold(report.appName)} ${chalk.dim(`(${report.bundleId})`)}`);
  lines.push(`  ${chalk.dim('Version:')}  ${chalk.white(report.version)} ${chalk.dim(`(${report.platform})`)}`);
  lines.push(`  ${chalk.dim('Date:')}     ${chalk.white(report.date)}`);
  lines.push('');

  // ─── Score ────────────────────────────────────────────────────────
  const emoji = getGradeEmoji(report.score);
  const scoreColor = report.score >= 90
    ? chalk.green
    : report.score >= 75
      ? chalk.yellow
      : report.score >= 50
        ? chalk.hex('#FF8C00')
        : chalk.red;

  lines.push(`  ${chalk.dim('Score:')}    ${scoreColor.bold(`${report.score}/100`)} ${emoji} ${chalk.bold(report.grade)} — ${chalk.italic(report.gradeLabel)}`);
  lines.push('');

  // ─── Summary Table ────────────────────────────────────────────────
  lines.push(chalk.dim('  ┌─────────────────────────┬────┬────┬────┬────┐'));
  lines.push(chalk.dim('  │') + chalk.bold(' Module                  ') + chalk.dim('│') + chalk.red.bold(' 🔴 ') + chalk.dim('│') + chalk.hex('#FF8C00').bold(' 🟠 ') + chalk.dim('│') + chalk.yellow.bold(' 🟡 ') + chalk.dim('│') + chalk.blue.bold(' ℹ️  ') + chalk.dim('│'));
  lines.push(chalk.dim('  ├─────────────────────────┼────┼────┼────┼────┤'));

  for (const result of report.results) {
    const c = result.findings.filter((f) => f.severity === 'critical').length;
    const h = result.findings.filter((f) => f.severity === 'high').length;
    const w = result.findings.filter((f) => f.severity === 'warning').length;
    const i = result.findings.filter((f) => f.severity === 'info').length;

    const hasIssues = c + h + w > 0;
    const nameStr = `${result.icon} ${result.label}`.padEnd(24);

    const colorize = hasIssues
      ? (s: string) => s
      : chalk.green;

    lines.push(
      chalk.dim('  │') +
      colorize(` ${nameStr}`) +
      chalk.dim('│') +
      ` ${c > 0 ? chalk.red.bold(String(c).padStart(2)) : chalk.dim(' ·')} ` +
      chalk.dim('│') +
      ` ${h > 0 ? chalk.hex('#FF8C00').bold(String(h).padStart(2)) : chalk.dim(' ·')} ` +
      chalk.dim('│') +
      ` ${w > 0 ? chalk.yellow.bold(String(w).padStart(2)) : chalk.dim(' ·')} ` +
      chalk.dim('│') +
      ` ${i > 0 ? chalk.blue(String(i).padStart(2)) : chalk.dim(' ·')} ` +
      chalk.dim('│'),
    );
  }

  lines.push(chalk.dim('  └─────────────────────────┴────┴────┴────┴────┘'));
  lines.push('');

  // ─── Totals ───────────────────────────────────────────────────────
  lines.push(`  ${chalk.dim('Total:')} ${chalk.red.bold(`${report.summary.critical} critical`)}${chalk.dim(',')} ${chalk.hex('#FF8C00').bold(`${report.summary.high} high`)}${chalk.dim(',')} ${chalk.yellow.bold(`${report.summary.warning} warning`)}${chalk.dim(',')} ${chalk.blue(`${report.summary.info} info`)}`);
  lines.push('');

  // ─── Findings by Severity ────────────────────────────────────────
  const severityOrder = ['critical', 'high', 'warning', 'info'] as const;
  const severityLabels = {
    critical: '🔴 Critical Findings',
    high: '🟠 High Findings',
    warning: '🟡 Warnings',
    info: 'ℹ️  Informational',
  };

  for (const severity of severityOrder) {
    const findings = report.findings.filter((f) => f.severity === severity);
    if (findings.length === 0) continue;

    lines.push(chalk.bold(`  ${severityLabels[severity]}`));
    lines.push(chalk.dim('  ─────────────────────────────────────────'));

    for (const finding of findings) {
      const emoji = getSeverityEmoji(finding.severity);
      lines.push(`  ${emoji} ${chalk.bold(`[${finding.id}]`)} ${finding.title}`);
      lines.push(`     ${chalk.dim(finding.message)}`);
      if (finding.remedy) {
        lines.push(`     ${chalk.green('→')} ${chalk.green(finding.remedy)}`);
      }
      lines.push('');
    }
  }

  // ─── Passed Modules ──────────────────────────────────────────────
  const passedModules = report.results.filter(
    (r) => r.findings.filter((f) => f.severity !== 'info').length === 0,
  );

  if (passedModules.length > 0) {
    lines.push(chalk.green.bold('  ✅ Passed Checks'));
    lines.push(chalk.dim('  ─────────────────────────────────────────'));
    for (const mod of passedModules) {
      lines.push(`  ${chalk.green('✓')} ${mod.icon} ${mod.label}`);
    }
    lines.push('');
  }

  lines.push(chalk.dim('  Generated by ASC Doctor • https://github.com/aykutbey3543/ascdoc'));
  lines.push('');

  return lines.join('\n');
}
