import { describe, it, expect } from 'vitest';
import { renderHTML } from '../../src/reporter/html.js';
import { generateDemoData } from '../../src/demo/data.js';
import { runAudit } from '../../src/auditors/index.js';

describe('renderHTML', async () => {
  const demoData = generateDemoData();
  const report = await runAudit(demoData, { only: [], skip: [] });

  it('renders a valid HTML document', () => {
    const html = renderHTML(report);
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<html lang="en">');
    expect(html).toContain('<title>ASC Doctor Report');
  });

  it('contains the score and grade', () => {
    const html = renderHTML(report);
    expect(html).toContain('/ 100');
    expect(html).toContain(report.grade);
    expect(html).toContain(report.gradeLabel);
  });

  it('contains the summary table', () => {
    const html = renderHTML(report);
    expect(html).toContain('Audit Summary');
    expect(html).toContain('Module');
    expect(html).toContain('Critical');
  });

  it('contains finding cards with remedies', () => {
    const html = renderHTML(report);
    // Search for a known demo finding ID or at least the remedy label
    expect(html).toContain('finding-card');
    expect(html).toContain('Fix:');
  });

  it('contains the footer with tool name', () => {
    const html = renderHTML(report);
    expect(html).toContain('Report generated by');
    expect(html).toContain('ASC Doctor');
  });
});
